/* 8aPDF Workspace v4 – additive UI layer. All existing school handlers remain mounted. */
(()=>{'use strict';
const $=id=>document.getElementById(id);
const STUDIO=()=>document.documentElement.dataset.uiMode==='studio';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=(key,def)=>{try{const o=JSON.parse(localStorage.getItem(key));return o===null?def:o}catch{return def}};
const put=(key,obj)=>{try{localStorage.setItem(key,JSON.stringify(obj))}catch{}};
const bridge=()=>window.__8apdfStudyBridge;
const prefKey='8apdf_ws_v4_preferences';const taskKey='8apdf_ws_v4_task_done';const customKey='8apdf_ws_v4_custom_tasks';
const def={theme:'system',boost:false,w:{timetable:true,teachers:true,recents:true,notes:false,planner:false,autoTodo:false}};
let pref={...def,...get(prefKey,{}),w:{...def.w,...get(prefKey,{})?.w}};
let messages=[],modal=null,modalBody=null,musicEngine=null,lastFocus=null,latestSummaryController=null;
const savePref=()=>put(prefKey,pref);
function showToast(text){if(typeof bridge()?.notify==='function')bridge().notify(text);else alert(text)}
function cacheStatus(){return !!bridge()?.isLive?.()}
function show(title,html){lastFocus=document.activeElement;if(!modal){modal=document.createElement('div');modal.className='ws-overlay';modal.hidden=true;modal.innerHTML='<section class="ws-dialog" role="dialog" aria-modal="true" aria-labelledby="wsDialogTitle"><div class="ws-dialog-head"><h2 id="wsDialogTitle"></h2><button type="button" id="wsClose" aria-label="Close">✕</button></div><div id="wsDialogBody"></div></section>';document.body.append(modal);modal.addEventListener('click',e=>{if(e.target===modal)close()});$('wsClose').addEventListener('click',close);modalBody=$('wsDialogBody')};$('wsDialogTitle').textContent=title;modalBody.innerHTML=html;modal.hidden=false;document.body.classList.add('no-scroll');$('wsClose').focus({preventScroll:true});return modalBody}
function close(){if(!modal||modal.hidden)return;modal.hidden=true;modalBody.replaceChildren();document.body.classList.remove('no-scroll');latestSummaryController?.abort();lastFocus?.focus?.({preventScroll:true})}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal&&!modal.hidden){e.preventDefault();close()}});
function syncDeviceTheme(){if(!STUDIO())return;if(pref.theme==='original'){document.documentElement.dataset.glass='off';document.documentElement.dataset.fluid='off';document.documentElement.dataset.wsBoost=pref.boost?'on':'off';return;}const value=pref.theme==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'pure-black'):pref.theme;const root=document.documentElement;root.dataset.theme=value;root.dataset.tone=value==='light'?'light':'dark';root.dataset.glass='off';root.dataset.fluid='off';root.dataset.wsBoost=pref.boost?'on':'off';document.querySelector('meta[name="theme-color"]')?.setAttribute('content',value==='light'?'#f7f7f7':'#000000')}
matchMedia('(prefers-color-scheme: light)').addEventListener?.('change',()=>{if(STUDIO())syncDeviceTheme()});
function settings(){const root=show('Simple Settings',`<p>Sirf useful controls. Advanced visual effects aur liquid glass hata diye gaye hain.</p><label class="ws-line"><span>Appearance<small>Follow your phone, or choose manually</small></span><select id="wsTheme"><option value="system">Device default</option><option value="pure-black">Dark</option><option value="light">Light</option><option value="original">Original theme colors</option></select></label><div class="ws-line"><span>All original theme colors<small>Choose from your existing palette and custom colors</small></span><button id="wsAllColors" type="button">Choose colors</button></div><label class="ws-line"><span>Boost performance<small>For older phones: reduce heavy effects and card animations</small></span><input type="checkbox" id="wsBoost"></label><label class="ws-line"><span>Motion<small>Keep original subtle transitions unless you turn them off</small></span><input type="checkbox" id="wsMotion" checked></label><div class="ws-line"><span>Clear temporary PDF/message cache<small>Does not erase your to-do completion or bookmarks</small></span><button id="wsClearCache">Clear cache</button></div><div class="ws-notice">All other features are available from the left sidebar. Your existing study data remains unchanged.</div>`);
$('wsAllColors').onclick=()=>{const original=document.getElementById('themeGrid');if(!original)return showToast('Theme palette not available yet');const themes=[...original.querySelectorAll('[data-theme-choice]')];show('Original Theme Colors',`<p>All ${themes.length} original theme presets. Select any color to apply it across the website.</p><div class="ws-color-grid">${themes.map(t=>`<button type="button" data-ws-palette="${esc(t.dataset.themeChoice)}">${t.innerHTML}</button>`).join('')}</div><div class="ws-line"><span>Custom color</span><input type="color" id="wsCustomColor" value="#7364cf"></div><button id="wsApplyCustom">Apply custom color</button>`);document.querySelector('.ws-color-grid').onclick=e=>{const b=e.target.closest('[data-ws-palette]');if(!b)return;original.querySelector('[data-theme-choice="'+b.dataset.wsPalette+'"]')?.click();pref.theme='original';savePref();syncDeviceTheme();showToast('Theme color applied')};$('wsApplyCustom').onclick=()=>{const picker=document.getElementById('customColor');if(!picker)return;picker.value=$('wsCustomColor').value;picker.dispatchEvent(new Event('input',{bubbles:true}));pref.theme='original';savePref();syncDeviceTheme();showToast('Custom color applied')}};
$('wsTheme').value=pref.theme;$('wsBoost').checked=pref.boost;$('wsMotion').checked=document.documentElement.dataset.motion!=='off';
$('wsTheme').onchange=e=>{pref.theme=e.target.value;savePref();syncDeviceTheme()};
$('wsBoost').onchange=e=>{pref.boost=e.target.checked;savePref();syncDeviceTheme();showToast(pref.boost?'Performance mode enabled':'Performance mode disabled')};
$('wsMotion').onchange=e=>{const on=e.target.checked;const state=get('8apdf_classic_glass_settings_v2',{});state.motion=!on;put('8apdf_classic_glass_settings_v2',state);document.documentElement.dataset.motion=on?'on':'off';showToast('Motion preference saved')};
$('wsClearCache').onclick=()=>{for(const k of ['8a_cache_pdfs','8a_cache_messages'])localStorage.removeItem(k);showToast('Cached previews cleared. Live library will load again on refresh.')};return root}
function docs(){return Array.isArray(bridge()?.documents?.())?bridge().documents():[]}
function allItems(){const result=[],already=new Set();for(const d of docs()){const id='pdf:'+d.id;if(already.has(id))continue;already.add(id);result.push({id,title:`${d.subject||'PDF'} · ${d.title||'Untitled PDF'}`,type:'PDF',timestamp:d.dateMs||0})}
for(const m of messages.filter(x=>x.published!==false)){const id='msg:'+m.id;if(already.has(id))continue;already.add(id);result.push({id,title:String(m.title||m.message||m.description||'Teacher update'),type:'Teacher',timestamp:Date.parse(m.createdAt?.seconds?m.createdAt.seconds*1000:m.createdAt||m.messageDate||0)||0})}
for(const t of get(customKey,[])){result.push({id:'own:'+t.id,title:t.text,type:'Personal',timestamp:t.time||0})}return result}
function renderTodo(){const records=allItems();const done=get(taskKey,{});const filter=$('wsTaskSearch')?.value.toLowerCase().trim()||'';const type=$('wsTaskKind')?.value||'all';const matched=records.filter(x=>(type==='all'||x.type===type)&&(!filter||x.title.toLowerCase().includes(filter)));const el=$('wsTaskList');if(!el)return;el.innerHTML=matched.slice(0,Number(el.dataset.limit||80)).map(x=>`<div class="ws-task"><input type="checkbox" data-ws-task="${esc(x.id)}" aria-label="Mark complete" ${done[x.id]?'checked':''}><label class="${done[x.id]?'done':''}">${esc(x.title)}<small>${esc(x.type)}</small></label>${x.type==='Personal'?`<button type="button" data-ws-remove="${esc(x.id)}" aria-label="Delete personal task">✕</button>`:''}</div>`).join('')||'<div class="ws-notice">No matching school tasks loaded yet. Check connection or add your own task.</div>';if(matched.length>Number(el.dataset.limit||80))el.insertAdjacentHTML('beforeend',`<button class="ws-quiet" style="margin-top:10px" data-ws-more>Show more (${matched.length-Number(el.dataset.limit||80)} remaining)</button>`);$('wsTaskCounter').textContent=`${Object.values(done).filter(Boolean).length} completed · ${records.length} total`}
function todo(){show('Auto To-Do & Study Checklist',`<p>School PDFs aur teacher messages automatic list mein aate hain. Custom tasks bhi add kar sakte ho. Completion iss device par save hoti hai.</p><div class="ws-cols"><input id="wsTaskSearch" type="search" placeholder="Search tasks or chapters"><select id="wsTaskKind"><option value="all">All tasks</option><option value="PDF">PDFs</option><option value="Teacher">Teacher messages</option><option value="Personal">Personal</option></select></div><form id="wsCustomForm" class="ws-line"><input id="wsNewTask" maxlength="160" required placeholder="Add a task, e.g. Finish Science Ch 8" style="flex:1"><button class="ws-primary" type="submit">Add</button></form><div id="wsTaskCounter" class="ws-tag"></div><div id="wsTaskList"></div>`);
$('wsTaskSearch').oninput=renderTodo;$('wsTaskKind').onchange=renderTodo;$('wsCustomForm').onsubmit=e=>{e.preventDefault();const text=$('wsNewTask').value.trim();if(!text)return;put(customKey,[...get(customKey,[]),{id:(crypto.randomUUID?.()||String(Date.now())),text,time:Date.now()}]);$('wsNewTask').value='';renderTodo()};
$('wsTaskList').onchange=e=>{const input=e.target.closest('[data-ws-task]');if(!input)return;const status=get(taskKey,{});status[input.dataset.wsTask]=input.checked;put(taskKey,status);renderTodo()};
$('wsTaskList').onclick=e=>{if(e.target.closest('[data-ws-more]')){$('wsTaskList').dataset.limit=String(Number($('wsTaskList').dataset.limit||80)+80);renderTodo();return}const b=e.target.closest('[data-ws-remove]');if(!b)return;const id=b.dataset.wsRemove.substring(4);put(customKey,get(customKey,[]).filter(x=>String(x.id)!==id));renderTodo()};renderTodo()}
function widgets(){const root=show('Edit Home Widgets',`<p>Welcome screen par kya dikhe? Choose karo. School data wahi original Firebase se aayega.</p><div id="wsWidgetToggles"></div><div class="ws-notice">Changes saved automatically on this device. All features sidebar se accessible rehte hain.</div>`);const names={timetable:'Class Timetable',teachers:'Teacher Messages',recents:'Latest PDFs',notes:'Quick Notes',planner:'Today / Tomorrow Tasks',autoTodo:'Automatic To-Do'};const el=$('wsWidgetToggles');el.innerHTML=Object.entries(names).map(([k,label])=>`<label class="ws-line"><span>${label}</span><input type="checkbox" data-ws-widget="${k}" ${pref.w[k]?'checked':''}></label>`).join('');el.onchange=e=>{const i=e.target.closest('[data-ws-widget]');if(!i)return;pref.w[i.dataset.wsWidget]=i.checked;savePref();applyWidgets()};return root}
function applyWidgets(){if(!STUDIO())return;const selectors={timetable:'#dashboardWidgets > .widget:nth-child(1)',teachers:'#dashboardWidgets > .widget:nth-child(2)',recents:'#dashboardWidgets > .widget:nth-child(3)',notes:'#dashboardWidgets > .widget:nth-child(4)',planner:'#newSchoolPlanner > .widget:nth-child(1)',autoTodo:'#newSchoolPlanner > .widget:nth-child(2)'};for(const [key,sel] of Object.entries(selectors))document.querySelector(sel)?.classList.toggle('ws-hidden-widget',!pref.w[key])}
function buildSidebar(){const side=$('studioSidebar');if(!side||$('wsExtraLinks'))return;const group=document.createElement('div');group.id='wsExtraLinks';group.className='studio-nav-group workspace-sidebar-group';group.innerHTML=`<span class="studio-nav-caption">STUDY ESSENTIALS</span><button type="button" class="studio-side-link" data-ws-action="todo"><span class="ws-icon">☑</span><span>All PDFs & To-Do</span></button><button type="button" class="studio-side-link" data-ws-action="zip"><span class="ws-icon">↓</span><span>Download PDF ZIP</span></button><button type="button" class="studio-side-link" data-ws-action="music"><span class="ws-icon">♫</span><span>Relaxing Sounds</span></button><button type="button" class="studio-side-link" data-ws-action="manual"><span class="ws-icon">↗</span><span>Send PDF File</span></button><button type="button" class="studio-side-link" data-ws-action="upload"><span class="ws-icon">♧</span><span>Upload & Public Short Link</span></button><button type="button" class="studio-side-link" data-ws-action="widgets"><span class="ws-icon">⊞</span><span>Edit Home Widgets</span></button>`;side.insertBefore(group,side.querySelector('.studio-side-end'));group.onclick=e=>{const b=e.target.closest('[data-ws-action]');if(!b)return;const action=b.dataset.wsAction;if(action==='todo')todo();else if(action==='zip')downloadZip();else if(action==='music')music();else if(action==='manual')manual();else if(action==='upload')upload();else if(action==='widgets')widgets();if(innerWidth<810)$('studioSidebarClose')?.click()};
}
function home(){const hero=document.querySelector('.hero .hero-inner');if(!hero||$('workspaceHomeActions'))return;const mobile=document.createElement('h2');mobile.className='ws-mobile-title';mobile.textContent='Your study space.';hero.querySelector('.eyebrow-pill')?.insertAdjacentElement('afterend',mobile);const div=document.createElement('div');div.id='workspaceHomeActions';div.innerHTML='<button type="button" class="ws-quiet" id="wsEditHome">✎ Edit home widgets</button>';hero.append(div);$('wsEditHome').onclick=widgets}
function downloadZip(){if(typeof window.__8apdfZipExport==='function')return window.__8apdfZipExport();$('zipExport')?.click();if(!$('zipExport'))showToast('PDF ZIP service not loaded')}
function manual(){show('Send a Complete PDF File',`<p>PDF link nahi—original PDF file phone ke Share Sheet se WhatsApp, Nearby Share ya supported app ko bhejo.</p><input type="file" id="wsManualFile" accept="application/pdf,.pdf"><div class="ws-tools" style="margin-top:14px"><button class="ws-primary" id="wsManualSend">Share PDF file</button></div><div id="wsManualStatus" class="ws-status" role="status"></div>`);
$('wsManualSend').onclick=async()=>{const file=$('wsManualFile').files?.[0],status=$('wsManualStatus');if(!file)return status.textContent='Please select a PDF first.';if(!file.name.toLowerCase().endsWith('.pdf'))return status.textContent='Only PDF files are allowed.';try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:file.name})}else{status.textContent='Your browser cannot directly share files. Open this page in a modern mobile browser and use Share.'}}catch(e){if(e.name!=='AbortError')status.textContent='Could not share file: '+e.message}}
}
function upload(){show('Upload PDF → Public Short Link',`<p>Upload your own PDF file. The generated link opens the full PDF and can be shared publicly. Upload permission is required to protect storage.</p><div class="ws-file-field"><label for="wsUploadFile">PDF file <small>Maximum 4 MB</small></label><input type="file" id="wsUploadFile" accept="application/pdf,.pdf"></div><label class="ws-line"><span>Admin Upload Code<small>Set PDF_UPLOAD_TOKEN in Vercel environment variables</small></span><input id="wsUploadCode" type="password" autocomplete="off" placeholder="Upload authorization"></label><div class="ws-tools" style="margin:12px 0"><button id="wsUploadSend" class="ws-primary">Upload & create short link</button></div><div id="wsUploadStatus" class="ws-status" role="status"></div><div id="wsUploadResult" class="ws-notice" hidden></div>`);
$('wsUploadSend').onclick=async()=>{const f=$('wsUploadFile').files?.[0],token=$('wsUploadCode').value.trim(),st=$('wsUploadStatus'),result=$('wsUploadResult'),btn=$('wsUploadSend');if(!f)return st.textContent='Choose a PDF file first.';if(f.size>4*1024*1024||!f.name.toLowerCase().endsWith('.pdf'))return st.textContent='PDF only, maximum 4 MB.';if(!token)return st.textContent='Admin Upload Code required. Set PDF_UPLOAD_TOKEN on Vercel first.';
btn.disabled=true;st.textContent='Uploading PDF securely…';try{const res=await fetch('/api/upload-pdf',{method:'POST',headers:{'content-type':'application/pdf','x-upload-token':token,'x-filename':encodeURIComponent(f.name),'x-owner-key':(localStorage.getItem('8apdf_short_links_owner_v1')||'')},body:f});const data=await res.json();if(!res.ok)throw Error(data.error||'Upload failed');const url=new URL(data.shortUrl,location.origin).href;st.textContent='Uploaded successfully. Public PDF link created.';result.hidden=false;result.replaceChildren();const p=document.createElement('p');p.textContent=url;const copy=document.createElement('button');copy.textContent='Copy short link';copy.onclick=async()=>{try{await navigator.clipboard.writeText(url);copy.textContent='Copied!'}catch{window.prompt('Copy link',url)}};const share=document.createElement('button');share.textContent='Share';share.onclick=async()=>{if(navigator.share)await navigator.share({title:f.name,url});else copy.click()};result.append(p,copy,document.createTextNode(' '),share)}catch(e){st.textContent='Upload not completed: '+e.message}finally{btn.disabled=false}}
}
function sounds(){return [['Gentle Rain','rain'],['Ocean Waves','waves'],['Warm Brown Noise','brown'],['Calm Wind','wind'],['Soft Night Ambience','night'],['Focus Soundscape','focus']]}
function stopSound(){try{musicEngine?.context?.close()}catch{}musicEngine=null;document.querySelectorAll('.ws-track').forEach(e=>e.classList.remove('active'))}
function playSound(mode,vol){stopSound();const AC=window.AudioContext||window.webkitAudioContext;if(!AC){showToast('Audio not supported in this browser');return}try{const ctx=new AC(),size=ctx.sampleRate*3,buff=ctx.createBuffer(1,size,ctx.sampleRate),data=buff.getChannelData(0);let last=0;for(let i=0;i<size;i++){const rnd=Math.random()*2-1;if(['brown','waves','wind','night'].includes(mode)){last=(last+.017*rnd)/1.017;data[i]=last*4.2}else data[i]=rnd}const src=ctx.createBufferSource();src.buffer=buff;src.loop=true;const filter=ctx.createBiquadFilter();filter.type=mode==='rain'?'highpass':'lowpass';filter.frequency.value=mode==='rain'?600:mode==='focus'?340:mode==='night'?220:mode==='wind'?440:850;const gain=ctx.createGain();gain.gain.value=(vol/100)*.19;src.connect(filter);filter.connect(gain);gain.connect(ctx.destination);src.start();const parts=[];if(mode==='night'||mode==='focus'||mode==='waves'){for(const freq of (mode==='focus'?[130.81,196]:mode==='night'?[110,165]:[82.41,123.47])){const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.value=(vol/100)*.015;o.connect(g);g.connect(ctx.destination);o.start();parts.push(o)}}musicEngine={context:ctx,src,gain,parts,mode};ctx.resume().catch(()=>{});}catch(e){showToast('Audio could not start: '+e.message)}}
function music(){show('Relaxing Background Sounds',`<p>6 offline-generated ambient soundscapes. Koi external MP3 stream nahi; volume low rakhna aur jab chaaho stop kar dena.</p><div id="wsSoundList">${sounds().map(([name,id])=>`<div class="ws-track ${musicEngine?.mode===id?'active':''}"><span>♫ ${esc(name)}</span><button type="button" data-ws-sound="${esc(id)}">Play</button></div>`).join('')}</div><label class="ws-line"><span>Volume</span><input type="range" id="wsVolume" value="45" min="0" max="100" aria-label="Sound volume"></label><div class="ws-tools"><button type="button" id="wsMusicStop">Stop sounds</button></div>`);
$('wsSoundList').onclick=e=>{const btn=e.target.closest('[data-ws-sound]');if(!btn)return;playSound(btn.dataset.wsSound,+$('wsVolume').value);document.querySelectorAll('.ws-track').forEach(row=>row.classList.toggle('active',row.querySelector('[data-ws-sound]')?.dataset.wsSound===btn.dataset.wsSound))};$('wsVolume').oninput=e=>{if(musicEngine)musicEngine.gain.gain.value=(+e.target.value/100)*.19};$('wsMusicStop').onclick=()=>{stopSound();showToast('Background sound stopped')}}
async function summarize(doc){if(!doc?.pdfUrl){return show('PDF Summary','<div class="ws-notice">The selected PDF has no accessible URL. Try opening the PDF directly.</div>')};latestSummaryController?.abort();const abort=new AbortController();latestSummaryController=abort;show('AI PDF Summary',`<p><strong>${esc(doc.title)}</strong></p><div class="ws-notice" id="wsSummaryStatus" role="status">Loading PDF text…</div><div id="wsSummaryResult"></div>`);const status=$('wsSummaryStatus'),result=$('wsSummaryResult');try{const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';const resp=await fetch('/api/download?url='+encodeURIComponent(doc.pdfUrl)+'&filename=summary.pdf',{signal:abort.signal});if(!resp.ok)throw Error('PDF download could not be accessed ('+resp.status+').');const bytes=await resp.arrayBuffer();if(bytes.byteLength>12*1024*1024)throw Error('PDF exceeds the safe summary size limit (12 MB).');status.textContent='Reading content from PDF…';const pdf=await pdfjs.getDocument({data:new Uint8Array(bytes)}).promise;let text='';for(let i=1;i<=Math.min(pdf.numPages,12)&&text.length<23000;i++){if(abort.signal.aborted)throw Error('Cancelled');const page=await pdf.getPage(i);const tc=await page.getTextContent();text+=`\nPage ${i}: `+tc.items.map(x=>x.str||'').join(' ').replace(/\s+/g,' ').slice(0,3500)}if(text.trim().length<80)throw Error('No readable text found. This may be a scanned PDF.');status.textContent='Gemini is preparing a short study summary…';const ai=await fetch('/api/pdf-summarize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:doc.title,text:text.slice(0,24000)}),signal:abort.signal});const obj=await ai.json();if(!ai.ok)throw Error(obj.error||'Gemini request failed.');status.textContent='Summary generated from '+Math.min(pdf.numPages,12)+' PDF page(s).';result.innerHTML='<div class="ws-notice" style="white-space:pre-wrap"></div>';result.firstChild.textContent=obj.summary;const copy=document.createElement('button');copy.textContent='Copy summary';copy.onclick=()=>navigator.clipboard?.writeText(obj.summary).then(()=>showToast('Summary copied')).catch(()=>{});result.append(copy)}catch(e){if(e.name==='AbortError'||abort.signal.aborted)return;if(status)status.textContent='Unable to summarize: '+e.message}}
function summaryClick(e){if(!STUDIO())return;const btn=e.target.closest('[data-pdf="summary"]');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();const id=btn.dataset.id;const doc=docs().find(x=>String(x.id)===String(id));if(!doc)return show('PDF Summary','<div class="ws-notice">Library is still loading. Try again when it connects.</div>');summarize(doc)}
function interceptSettings(e){if(!STUDIO())return;const b=e.target.closest('#settingsBtn,[data-go="settings"],#settingsBack');if(!b)return;if(b.id==='settingsBack')return;e.preventDefault();e.stopImmediatePropagation();settings()}
function notifyUpdates(e){if(Array.isArray(e.detail))messages=e.detail;if(modal&&!modal.hidden&&$('wsTaskList'))renderTodo()}
function appInit(){if(!$('studioSidebar')||!$('dashboardWidgets'))return;buildSidebar();if(STUDIO()){document.querySelectorAll('.studio-sidebar [data-go="announcements"] span').forEach(el=>el.textContent="Teacher Messages");document.querySelectorAll('.studio-mobile-nav [data-go="announcements"] span').forEach(el=>el.textContent="Messages");const subtitle=document.querySelector('.hero p');if(subtitle)subtitle.textContent="Your PDFs, study notes and teacher messages—one peaceful place to learn."}home();applyWidgets();syncDeviceTheme();document.addEventListener('8apdf:teacher-data',notifyUpdates);try{messages=get('8a_cache_messages',[])}catch{};document.addEventListener('8apdf:library-updated',()=>{if(modal&&!modal.hidden&&$('wsTaskList'))renderTodo()});document.addEventListener('click',summaryClick,true);document.addEventListener('click',interceptSettings,true);document.querySelectorAll('.pdf-card').forEach(card=>{if(!card.querySelector('.pdf-summary-utility')){const id=card.querySelector('[data-pdf]')?.dataset.id;if(id)card.insertAdjacentHTML('beforeend',`<button class="pdf-summary-utility" data-pdf="summary" data-id="${esc(id)}">✧ Summarize PDF</button>`)}});if(window.MutationObserver){const grid=$('pdfGrid');const o=new MutationObserver(()=>{grid?.querySelectorAll('.pdf-card').forEach(card=>{if(!card.querySelector('[data-pdf="summary"]')){const id=card.querySelector('[data-pdf]')?.dataset.id;if(id)card.insertAdjacentHTML('beforeend',`<button class="pdf-summary-utility" data-pdf="summary" data-id="${esc(id)}">✧ Summarize PDF</button>`)}})});if(grid)o.observe(grid,{childList:true})}
}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&musicEngine?.context?.state==='running')musicEngine.context.suspend().catch(()=>{});else if(!document.hidden&&musicEngine?.context?.state==='suspended')musicEngine.context.resume().catch(()=>{})});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',appInit,{once:true});else appInit();
})();