package com.eightapdf.gold

import android.content.Context
import kotlin.random.Random

object QuoteRepository {
    private const val PREFS = "daily_motivation"
    private const val ORDER = "rotation_order"
    private const val INDEX = "rotation_index"
    private const val LAST_DATE = "last_sent_date"
    val quotes = listOf(
        "Your future starts with what you study today. 📚",
        "Small efforts every day create extraordinary results. 🔥",
        "Your dreams deserve your hard work. 👑",
        "Make this study session count.",
        "Progress grows quietly through consistent practice.",
        "You are capable of learning difficult things.",
        "One focused hour can change your whole week.",
        "Keep going; your future self is cheering for you.",
        "A little revision today makes tomorrow easier.",
        "Discipline turns big dreams into daily steps.",
        "Every solved question builds your confidence.",
        "Study with patience and finish with pride.",
        "You do not need perfection; you need a beginning.",
        "Your effort is stronger than your excuses.",
        "Learn today so opportunities find you tomorrow.",
        "The chapter feels easier after the first page.",
        "Focus on the next small step.",
        "Your consistency is your secret advantage.",
        "Hard work becomes confidence when you keep showing up.",
        "A calm mind and a clear plan can solve a lot.",
        "Your future starts with what you study today. 📚 Keep learning, one page at a time.",
        "Small efforts every day create extraordinary results. 🔥 Stay patient and keep moving.",
        "Your dreams deserve your hard work. 👑 You are closer than you think.",
        "Make this study session count Make yourself proud today.",
        "Progress grows quietly through consistent practice Keep your goal close.",
        "You are capable of learning difficult things Trust the process.",
        "One focused hour can change your whole week Your effort will add up.",
        "Keep going; your future self is cheering for you Start with ten focused minutes.",
        "A little revision today makes tomorrow easier Keep learning, one page at a time.",
        "Discipline turns big dreams into daily steps Stay patient and keep moving.",
        "Every solved question builds your confidence You are closer than you think.",
        "Study with patience and finish with pride Make yourself proud today.",
        "You do not need perfection; you need a beginning Keep your goal close.",
        "Your effort is stronger than your excuses Trust the process.",
        "Learn today so opportunities find you tomorrow Your effort will add up.",
        "The chapter feels easier after the first page Start with ten focused minutes.",
        "Focus on the next small step Keep learning, one page at a time.",
        "Your consistency is your secret advantage Stay patient and keep moving.",
        "Hard work becomes confidence when you keep showing up You are closer than you think.",
        "A calm mind and a clear plan can solve a lot Make yourself proud today.",
        "Your future starts with what you study today. 📚 Keep your goal close.",
        "Small efforts every day create extraordinary results. 🔥 Trust the process.",
        "Your dreams deserve your hard work. 👑 Your effort will add up.",
        "Make this study session count Start with ten focused minutes.",
        "Progress grows quietly through consistent practice Keep learning, one page at a time.",
        "You are capable of learning difficult things Stay patient and keep moving.",
        "One focused hour can change your whole week You are closer than you think.",
        "Keep going; your future self is cheering for you Make yourself proud today.",
        "A little revision today makes tomorrow easier Keep your goal close.",
        "Discipline turns big dreams into daily steps Trust the process.",
        "Every solved question builds your confidence Your effort will add up.",
        "Study with patience and finish with pride Start with ten focused minutes.",
        "You do not need perfection; you need a beginning Keep learning, one page at a time.",
        "Your effort is stronger than your excuses Stay patient and keep moving.",
        "Learn today so opportunities find you tomorrow You are closer than you think.",
        "The chapter feels easier after the first page Make yourself proud today.",
        "Focus on the next small step Keep your goal close.",
        "Your consistency is your secret advantage Trust the process.",
        "Hard work becomes confidence when you keep showing up Your effort will add up.",
        "A calm mind and a clear plan can solve a lot Start with ten focused minutes.",
        "Your future starts with what you study today. 📚 Keep learning, one page at a time.",
        "Small efforts every day create extraordinary results. 🔥 Stay patient and keep moving.",
        "Your dreams deserve your hard work. 👑 You are closer than you think.",
        "Make this study session count Make yourself proud today.",
        "Progress grows quietly through consistent practice Keep your goal close.",
        "You are capable of learning difficult things Trust the process.",
        "One focused hour can change your whole week Your effort will add up.",
        "Keep going; your future self is cheering for you Start with ten focused minutes.",
        "A little revision today makes tomorrow easier Keep learning, one page at a time.",
        "Discipline turns big dreams into daily steps Stay patient and keep moving.",
        "Every solved question builds your confidence You are closer than you think.",
        "Study with patience and finish with pride Make yourself proud today.",
        "You do not need perfection; you need a beginning Keep your goal close.",
        "Your effort is stronger than your excuses Trust the process.",
        "Learn today so opportunities find you tomorrow Your effort will add up.",
        "The chapter feels easier after the first page Start with ten focused minutes.",
        "Focus on the next small step Keep learning, one page at a time.",
        "Your consistency is your secret advantage Stay patient and keep moving.",
        "Hard work becomes confidence when you keep showing up You are closer than you think.",
        "A calm mind and a clear plan can solve a lot Make yourself proud today.",
        "Your future starts with what you study today. 📚 Keep your goal close.",
        "Small efforts every day create extraordinary results. 🔥 Trust the process.",
        "Your dreams deserve your hard work. 👑 Your effort will add up.",
        "Make this study session count Start with ten focused minutes.",
        "Progress grows quietly through consistent practice Keep learning, one page at a time.",
        "You are capable of learning difficult things Stay patient and keep moving.",
        "One focused hour can change your whole week You are closer than you think.",
        "Keep going; your future self is cheering for you Make yourself proud today.",
        "A little revision today makes tomorrow easier Keep your goal close.",
        "Discipline turns big dreams into daily steps Trust the process.",
        "Every solved question builds your confidence Your effort will add up.",
        "Study with patience and finish with pride Start with ten focused minutes.",
        "You do not need perfection; you need a beginning Keep learning, one page at a time.",
        "Your effort is stronger than your excuses Stay patient and keep moving.",
        "Learn today so opportunities find you tomorrow You are closer than you think.",
        "The chapter feels easier after the first page Make yourself proud today.",
        "Focus on the next small step Keep your goal close.",
        "Your consistency is your secret advantage Trust the process.",
        "Hard work becomes confidence when you keep showing up Your effort will add up.",
        "A calm mind and a clear plan can solve a lot Start with ten focused minutes.",
        "Your future starts with what you study today. 📚 Keep learning, one page at a time.",
        "Small efforts every day create extraordinary results. 🔥 Stay patient and keep moving.",
        "Your dreams deserve your hard work. 👑 You are closer than you think.",
        "Make this study session count Make yourself proud today.",
        "Progress grows quietly through consistent practice Keep your goal close.",
        "You are capable of learning difficult things Trust the process.",
        "One focused hour can change your whole week Your effort will add up.",
        "Keep going; your future self is cheering for you Start with ten focused minutes.",
        "A little revision today makes tomorrow easier Keep learning, one page at a time.",
        "Discipline turns big dreams into daily steps Stay patient and keep moving.",
        "Every solved question builds your confidence You are closer than you think.",
        "Study with patience and finish with pride Make yourself proud today.",
        "You do not need perfection; you need a beginning Keep your goal close.",
        "Your effort is stronger than your excuses Trust the process.",
        "Learn today so opportunities find you tomorrow Your effort will add up.",
        "The chapter feels easier after the first page Start with ten focused minutes.",
        "Focus on the next small step Keep learning, one page at a time.",
        "Your consistency is your secret advantage Stay patient and keep moving.",
        "Hard work becomes confidence when you keep showing up You are closer than you think.",
        "A calm mind and a clear plan can solve a lot Make yourself proud today.",
        "Your future starts with what you study today. 📚 Keep your goal close.",
        "Small efforts every day create extraordinary results. 🔥 Trust the process.",
        "Your dreams deserve your hard work. 👑 Your effort will add up.",
        "Make this study session count Start with ten focused minutes.",
        "Progress grows quietly through consistent practice Keep learning, one page at a time.",
        "You are capable of learning difficult things Stay patient and keep moving.",
        "One focused hour can change your whole week You are closer than you think.",
        "Keep going; your future self is cheering for you Make yourself proud today.",
        "A little revision today makes tomorrow easier Keep your goal close.",
        "Discipline turns big dreams into daily steps Trust the process.",
        "Every solved question builds your confidence Your effort will add up.",
        "Study with patience and finish with pride Start with ten focused minutes.",
        "You do not need perfection; you need a beginning Keep learning, one page at a time.",
        "Your effort is stronger than your excuses Stay patient and keep moving.",
        "Learn today so opportunities find you tomorrow You are closer than you think.",
        "The chapter feels easier after the first page Make yourself proud today.",
        "Focus on the next small step Keep your goal close.",
        "Your consistency is your secret advantage Trust the process.",
        "Hard work becomes confidence when you keep showing up Your effort will add up.",
        "A calm mind and a clear plan can solve a lot Start with ten focused minutes.",
        "Your future starts with what you study today. 📚 Keep learning, one page at a time.",
        "Small efforts every day create extraordinary results. 🔥 Stay patient and keep moving.",
        "Your dreams deserve your hard work. 👑 You are closer than you think.",
        "Make this study session count Make yourself proud today.",
        "Progress grows quietly through consistent practice Keep your goal close.",
        "You are capable of learning difficult things Trust the process.",
        "One focused hour can change your whole week Your effort will add up.",
        "Keep going; your future self is cheering for you Start with ten focused minutes.",
        "A little revision today makes tomorrow easier Keep learning, one page at a time.",
        "Discipline turns big dreams into daily steps Stay patient and keep moving.",
        "Every solved question builds your confidence You are closer than you think.",
        "Study with patience and finish with pride Make yourself proud today.",
        "You do not need perfection; you need a beginning Keep your goal close.",
        "Your effort is stronger than your excuses Trust the process.",
        "Learn today so opportunities find you tomorrow Your effort will add up.",
        "The chapter feels easier after the first page Start with ten focused minutes.",
        "Focus on the next small step Keep learning, one page at a time.",
        "Your consistency is your secret advantage Stay patient and keep moving.",
        "Hard work becomes confidence when you keep showing up You are closer than you think.",
        "A calm mind and a clear plan can solve a lot Make yourself proud today.",
    )

    fun next(context: Context, dateKey: String): String {
        val prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        if (prefs.getString(LAST_DATE, "") == dateKey) return ""
        val saved = prefs.getString(ORDER, null)
        var order = saved?.split(',')?.mapNotNull { it.toIntOrNull() }?.toMutableList()
        if (order == null || order.size != quotes.size || order.toSet().size != quotes.size) {
            order = quotes.indices.shuffled(Random(System.currentTimeMillis())).toMutableList()
            prefs.edit().putString(ORDER, order.joinToString(",")).putInt(INDEX, 0).apply()
        }
        var index = prefs.getInt(INDEX, 0)
        if (index >= order.size) {
            order = quotes.indices.shuffled(Random(System.currentTimeMillis())).toMutableList()
            index = 0
            prefs.edit().putString(ORDER, order.joinToString(",")).apply()
        }
        val quote = quotes[order[index]]
        prefs.edit().putInt(INDEX, index + 1).putString(LAST_DATE, dateKey).apply()
        return quote
    }
}
